elixir-lsp/elixir_sense

lib/elixir_sense/core/source.ex, lib/elixir_sense/core/tokenizer.ex, test/elixir_sense/core/source_test.exs, test/elixir_sense/core/tokenizer_test.exs
The main fix is that Elixir 1.6.x and on returns a two tuple from `:elixir_tokenizer.tokenize/3` whereas before that it returned a four tuple.
Submitted upstream as: https://github.com/msaraiva/elixir_sense/pull/38
=> Extract :elixir_tokenizer and parse based on running version

.travis.yml
Apparently Travis will export the variables in `env` in a random order. Therefore we can't rely on the order and each environment variable needs to stand on its own.
Here's an example run where the environment variables were export "out of order":
https://travis-ci.com/elixir-lsp/elixir_sense/jobs/171597380
```
$ export MIX=${EX_BIN}/mix
$ export ELIXIR=${EX_BIN}/elixir
$ export EX_BIN=${EX_HOME}/bin
$ export EX_VSN=1.7.1
$ export EX_HOME=${TRAVIS_BUILD_DIR}/elixir
```
So because `EX_BIN` was exported after `ELIXIR`, `ELIXIR` was defined as simply `/elixir` which is incorrect. I fixed this by making each environment variable not depend on another.
=> Fix travis build reliability

.tool-versions, .travis.yml, test/elixir_sense/core/introspection_test.exs, test/elixir_sense/docs_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs, test/support/empty_module.ex, test/support/example_behaviour.ex
The good news is that none of the tests appear to have any real breakage on 1.8.0, it was just a matter of fixing the tests to not inspect Elixir's code/docs.
=> Fix tests for Elixir 1.8.0

.gitignore, lib/alchemist/helpers/complete.ex, lib/elixir_sense/core/normalized/code.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/providers/definition.ex, lib/elixir_sense/providers/docs.ex, lib/elixir_sense/providers/references.ex, lib/elixir_sense/providers/suggestion.ex, test/alchemist/helpers/complete_test.ex, test/alchemist/helpers/complete_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
`Alchemist.Completer` was based on `IEx.Autocomplete` from Elixir v~1.1. This PR:
- ports relevant changes and fixes from upstream Elixir until v1.9:
- improved struct handling
- improved completion for erlang modules
- fixed crash when completing deep not existing module
- do not hint invalid module names
- saner appending `.` after completion
- hidden functions are not suggested (`@doc false`, underscored with no docs)
- default argument functions with `@doc false` are not suggested
- fixed type for macros when docs are not available
- properly return suggestions for multi-arity functions
- ports tests from `IEx.Autocomplete`
- adds integration tests
- fixes an issue in `Introspection.get_docs` shim uncovered when porting changes
=> Port tests and fixes from iex

lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/suggestions_test.exs
This PR:
- adds support for alias shadowing (https://github.com/JakeBecker/elixir-ls/issues/172)
- fixes submodule aliases leaking into parent module scope
- fixes submodules incorrectly getting parent module alias
- creates alias for imported modules
- fixes handing of duplicated aliases, requires, imports and behaviors
=> Improve state tracking during metadata build

lib/elixir_sense/core/metadata_builder.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/suggestions_test.exs
This PR adds support for variable suggestions in
```
def my(arg), do: arg
```
and
```
case x do
var -> var
```
It also extends variable tracking test suite in metadata builder and fixes a few commented out assertions.
=> Improve var suggestions when used on the same line

lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/source.ex, test/elixir_sense/core/metadata_test.exs, test/elixir_sense/core/parser_test.exs, test/elixir_sense/suggestions_test.exs
This PR improves parse error recovery in a few common cases. It should make it more likely that valid suggestions are provided in case of unmatched ', ", [], (), do end.
Unfortunately I'm afraid it's not possible to make it much better in the current design, i.e. calling elixir parser `Code.string_to_quoted` and modifying source.
Elixir parser is not optimised for handling incomplete and invalid source and error messages are often incomplete.
=> Improve parser error recovery and suggestions in incomplete code

lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/state.ex, test/elixir_sense/core/parser_test.exs
If after parsing and metadata extraction we don't have line metadata and by inserting marker we introduce a parse error try to get env from previous lines. It's not certain but likely that it will be a good guess.
Fixes issue mentioned in https://github.com/elixir-lsp/elixir_sense/pull/21
=> Fallback strategy for line env

lib/elixir_sense/core/metadata_builder.ex, test/elixir_sense/core/metadata_builder_test.exs
It turns out `defguard` and `defguardp` create different AST than other defs
=> Adds support for defguard in metadata builder

lib/alchemist/helpers/complete.ex, lib/elixir_sense.ex, lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/suggestion.ex, test/alchemist/helpers/complete_test.exs, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
I noticed that module, function and macro suggestions only work for compiled modules. This is irritating when working on unfinished code. With the changes from this PR we are able to make suggestions basing on metadata from currently evaluated piece of code as a fallback if the module is not compiled.
I also did some refactoring in Complete module, most noticeably the aliases are no longer passed through application env
=> Suggest funs and modules from metadata

lib/alchemist/helpers/complete.ex, lib/elixir_sense.ex, lib/elixir_sense/core/introspection.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/suggestion.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
With this PR metadata builder is extended to extract info about encountered protocols and implementations. Unfortunately, protocols are quite complicated and in some cases are governed by different rules than regular modules, e.g. you can implement a protocol inside a protocol implementation or implement a protocol for more than one data type which. Those cases are equivalent to defining many modules and functions with the same lines of code. I had to do some tricky encoding to get it right in the current model. While doing so I encountered a bug with alias handling - collected aliases were not utilised properly resulting in badly aliased imports, requires and aliases referring to earlier aliases.
With metadata about protocols we can properly suggest protocol modules, functions and vars …
=> Add support for protocols

lib/elixir_sense/core/ast.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/suggestion.ex, test/elixir_sense/core/metadata_builder_test.exs, test/support/example_behaviour.ex
This PR extends metadata builder `use` directive comprehension. This allows for extraction of aliases, module attributes, submodules and functions defined in `__using__/1` (with some limitations, notably `defdelegate`, nested submodules and functions defined in submodules, as expanded macro results in different AST that directly calls into internal compiler APIs).
=> Use expansion improvements

lib/elixir_sense.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/suggestion.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/core/source_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
With this PR elixir_sense is able to produce suggestions for struct fields of metadata modules. It also fixes not always working multiline field suggestions and a crash in struct update syntax
=> Suggest struct fields from metadata

lib/elixir_sense.ex, lib/elixir_sense/core/metadata_builder.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/references_test.exs, test/support/modules_with_references.ex
With this PR elixir_sense will track function calls by `|>` operator and function captures by `&Mod.fun/arity`
=> Track pipe and capture calls

mix.exs
=> Use nesting in documentation to handle the long module names

lib/elixir_sense.ex, lib/elixir_sense/providers/eval.ex
It currently returns a string not bindings
=> Fix typespecs for match

lib/elixir_sense/providers/references.ex
Not sure how to create a test for this since we don't have any sample projects or anything.
=> Find references in umbrella projects

lib/elixir_sense.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/providers/definition.ex, test/elixir_sense/core/source_test.exs, test/elixir_sense/definition_test.exs
This PR adds support for finding definitions of functions and modules defined in the current file and not yet compiled. It also fixes an issue when trying to find definition for a local function call when there is a variable with the same name (as long as the call is of the form `my_func()`, there is no ambiguity as to call avariable we need `my_func.()`).
While working on this PR I also found an issue with `Source.split_module_and_func/2` - it failed to properly handle `__MODULE__`. I fixed that and added tests.
=> Find definitions for functions and modules from metadata

lib/elixir_sense/core/ast.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/core/source_test.exs, test/elixir_sense/suggestions_test.exs, test/support/example_behaviour.ex
Elixir allows defining erlang style modules with
```
defmodule :my_module do
```
as well as aliasing/requiring/importing such modules.
Fixes https://github.com/elixir-lsp/elixir_sense/issues/48
=> Add support for atoms as module names

lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/providers/suggestion.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/suggestions_test.exs
This PR fixes metadata call detection of calls with `__MODULE__.fun` form (and also calls of funcs from erlang modules)
Moreover it adds support for completion of funcs and submodules from `__MODULE__`
=> __MODULE__ improvements

lib/alchemist/helpers/module_info.ex, lib/elixir_sense.ex, lib/elixir_sense/core/introspection.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/providers/definition.ex, lib/elixir_sense/providers/docs.ex, lib/elixir_sense/providers/references.ex, lib/elixir_sense/providers/signature.ex, lib/elixir_sense/providers/suggestion.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/definition_test.exs, test/elixir_sense/references_test.exs, test/elixir_sense/signature_test.exs, test/support/module_with_builtin_type_shadowing.ex, test/support/modules_with_references.ex
This PR changes order of returned funs - now builtin types are tried after local functions. Previous implementation returned `{mod, fun}` regardless if the function existed or not. Now metadata is used to verify that.
While working on this i added a few tests and noticed that finding references for imported functions was not working. It turned out that `Source.subject_and_pos returned` wrong column for the call and there was some inconsistency in how call positions were stored in metadata.
I also had to fix `ModuleInfo.get_module_funs` as it was crashing when called for erlang modules
Fixes https://github.com/elixir-lsp/elixir_sense/issues/42
Resolves https://github.com/elixir-lsp/elixir_sense/pull/43
=> Use metadata in Introspection.actual_mod_fun

lib/alchemist/helpers/module_info.ex, lib/elixir_sense.ex, lib/elixir_sense/core/introspection.ex, lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/definition.ex, lib/elixir_sense/providers/docs.ex, lib/elixir_sense/providers/references.ex, lib/elixir_sense/providers/signature.ex, lib/elixir_sense/providers/suggestion.ex, test/alchemist/helpers/module_info_test.exs, test/elixir_sense/core/introspection_test.exs, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/definition_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
This PR extends metadata builder to collect typespec info. It was relatively easy to use this in suggestion and definition providers. I also fixed some corner cases and added tests to alias expansion.
=> Provide suggestions and definitions for typespecs from metadata

lib/elixir_sense/core/introspection.ex, lib/elixir_sense/core/type_info.ex, test/elixir_sense/signature_test.exs
As long as EEP 48 is not implemented in erlang, getting docs for erlang functions always fails with `{:error, :chunk_not_found}`. This PR adds fallback to typespecs that we are able to return at least something of a value.
=> Provide signatures for erlang functions

lib/elixir_sense/core/introspection.ex, lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/type_info.ex, lib/elixir_sense/providers/definition.ex, test/elixir_sense/definition_test.exs, test/support/macro_generated.ex
With this PR definition provider is able to get definitions of types from erlang modules. Moreover, I was able to improve definition retrieval from erlang modules in case of preloaded modules (by using `:code.get_object_code/1` instead of `:code.which/1`).
For elixir types I implemented a mechanism similar to the one used for functions and modules i.e. try metadata and fall back to docs.
=> Provide definitions for erlang types

.tool-versions, .travis.yml
If you wish 😁
PS: locally I've been running it for a while on macOS Catalina without noticing any problems (elixir `1.9.4`, first with erlang `22.1.8`, then with `22.2.1`).
=> Update elixir and otp versions in .tool-versions and .travis.yml

lib/elixir_sense/providers/suggestion.ex
This should unbreak the build 🙂
```
lib/elixir_sense/providers/suggestion.ex:338:call
The function call will not succeed.
:erlang.--([:__struct__], _fields_so_far :: atom())
will never return since it differs in arguments with
positions 2nd from the success typing arguments:
([any()], [any()])
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```
```elixir
{:_, fields_so_far, false} ->
result =
[:__struct__]
|> Kernel.--(fields_so_far)
|> Enum.filter(fn field -> String.starts_with?("#{field}", hint) end)
```
The problem is that `fields_so_far` is expected to come from `Source.which_struct`, but it can also be a response from `Introspection.actual_mod_fun`. This guard removes the ambiguity.
=> Fix dialyzer error

lib/elixir_sense/core/normalized/code.ex, test/elixir_sense/docs_test.exs, test/support/example_behaviour.ex
This PR aims to improve docs fetching when docs are not available in the module itself, but they can be derived from callback docs of the behaviour module.
A typical example of this is the repo module. For example, currently, vscode-elixirls produces the following:
With these changes, it can fetch docs from the behaviour module:
Testing this manually with VSCode turned out to be quite a challenge. It appears that this project moved much further compared to elixir-ls, so I ultimately had to create a temporary branch in the past. Even with that, I got some compilation warnings in elixir-ls, and some exceptions in VSCode, but this particular functionality seems to work correctly. My impression is that these exceptions are a consequence of sync loss between elixir-ls master and elixir_sense, …
=> Fetch docs from behaviour callback docs

.tool-versions, lib/elixir_sense/core/binding.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/core/struct.ex, lib/elixir_sense/providers/references.ex, lib/elixir_sense/providers/suggestion.ex, lib/elixir_sense/providers/suggestion/complete.ex, run.exs, test/elixir_sense/core/binding_test.exs, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/core/source_test.exs, test/elixir_sense/definition_test.exs, test/elixir_sense/providers/suggestion/complete_test.exs, test/elixir_sense/suggestions_test.exs, test/support/functions_with_return_spec.ex, test/support/module_with_struct.ex
With this PR elixir_sense is able to use typespecs to statically infere types of variables and use that info in suggestions engine. e.g. with code like
```
var = DateTime.utc_now()
var.h
^
```
the suggestions engine is able to complete struct field `hour`
=> Introduce a simple static type analyser

lib/elixir_sense.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/reducers/common.ex, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs, test/support/functions_with_the_same_name.ex
This PR creates a new field `def_arity` for function/macro suggestions. The `def_arity` represents the arity of the original function as it was defined. 
For context, the reason we need this is that we can have two times of functions with the same name:
1. A function with default arguments which generates multiple derived functions with different arities. The derived functions share the same metadata, including documentation and spec, e.g. `Enum.all?/2` generates `Enum.all?/1` and `Enum.all?/2`.
2. Independent functions with the same name but different arities. Although they have the same name, they don't share the same metadata, e.g. `Enum.concat/1` and `Enum.concat/2`.
The problem with the current implementation is that it generates suggestions for all of those functions without keeping …
=> Add def_arity to func suggestion

test/server_test.exs
This pull request makes the success of [`test/server_test.exs:38`](https://github.com/elixir-lsp/elixir_sense/blob/master/test/server_test.exs#L38) independent of project root name.
Running the aforementioned test inside `docker run -it -v $(pwd):/project_name_of_your_choosing elixir bash` no longer fails.
The rationale is the same for preferring `__MODULE__` over unaliased literal module name.
The [alias](https://dockyard.com/blog/2017/08/15/elixir-tips) here could be achieved by something along the following lines:
```elixir
project_root = Path.expand(Path.join(__ENV__.file, "../.."))
assert file =~ "#{project_root}/test/support/module_with_functions.ex"
```
The above alternative would couple to test file path, making it position-dependent, in addition to being a bit more verbose in …
=> decouple make test/server_test.exs:38 from project root name

lib/elixir_sense.ex, lib/elixir_sense/core/introspection.ex, lib/elixir_sense/location.ex, lib/elixir_sense/providers/definition.ex, lib/elixir_sense/providers/implementation.ex, lib/elixir_sense/server/request_handler.ex, run.exs, test/elixir_sense/core/introspection_test.exs, test/elixir_sense/definition_test.exs, test/elixir_sense/implementation_test.exs, test/server_test.exs, test/support/example_protocol.ex
Adds a new provider returning:
- behaviour implementations
- behaviour callback implementations
- protocol implementations
- protocol function implementations
- delegatees defined by defdelegate
Removes delegate support from definitions provider.
Changes definitions to return nil if not found.
Relevant discussions in https://github.com/elixir-lsp/elixir-ls/issues/132
I will follow with a PR to elixirLS when this one is merged
=> Add implementations provider

lib/elixir_sense/plugins/ecto/query.ex, test/elixir_sense/plugins/ecto_test.exs, test/support/plugins/ecto/fake_schemas.ex
Using ElixirLS with VS Code, I noticed that schemas with a many_to_many relationship weren't getting autocompletions as I composed ecto queries.
The output was complaining about the `%ManyToMany{}` struct not having a `:related_key`, and I traced it back to here. I've confirmed that this change does fix the issue and allows you to get autocompletions for schemas with `many_to_many` relationships.
=> Fix autocomplete for many_to_many associations

lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/matcher.ex, test/elixir_sense/providers/suggestion/complete_test.exs, test/elixir_sense/providers/suggestion/matcher_test.exs, test/elixir_sense/providers/suggestion_test.exs, test/elixir_sense/suggestions_test.exs
related: https://github.com/elixir-lsp/elixir-ls/issues/466
Only applied fuzzy matching on module functions so far.
All these files could use this polish to enhance UX. How far do we want to go in 1 PR?
- lib/elixir_sense/plugins/option.ex
- lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
- lib/elixir_sense/providers/suggestion/reducers/struct.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/overridable.ex
- lib/elixir_sense/providers/suggestion/reducers/protocol.ex
- lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- lib/elixir_sense/plugins/ecto/schema.ex
=> Fuzzy matching

lib/elixir_sense.ex, lib/elixir_sense/providers/references.ex, test/elixir_sense/references_test.exs
> _Does exactly what it says on the tin_
Currently, trying to retrieve references for a private function returns no results. I frequently want to do this inside large files, and so made this change such that finding references to a private function returns a list of results.
The implementation is largely inspired by the functionality for finding references to variables and attributes.
=> Add support for finding references to private functions

lib/elixir_sense/core/metadata_builder.ex
I'm not sure what `:struct` really refers to in this case, just guessing the version number could be a typo.
=> Fix possible typo

lib/elixir_sense/core/binding.ex, test/elixir_sense/core/binding_test.exs, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/providers/suggestion/complete_test.exs
Implements https://github.com/elixir-lsp/elixir-ls/issues/541
This PR adds basic inference when doing dependency injection using module attributes that calls into `Application.compile_env/3`, `Application.compile_env!/2`, `Application.get_env/3``and `Application.fetch_env!/2`. It works by calling the function and returning the resulting module as the expression type
=> Add inference when using dependency injection via module attribute

lib/elixir_sense/core/type_info.ex, mix.exs, test/elixir_sense/core/type_info_test.exs
Hi there!
Every time when I was creating a typespec with `any()` in some part of it, the lang server would error out with the following message:
```
LSP :: Error from the Language Server: an exception was raised:
** (CaseClauseError) no case clause matching: %{doc: "The top type, the set of all terms", params: []}
(elixir_sense 2.0.0) lib/elixir_sense/core/type_info.ex:113: anonymous fn/3 in ElixirSense.Core.TypeInfo.get_signatures/3
(elixir 1.12.0) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
(elixir_sense 2.0.0) lib/elixir_sense/core/type_info.ex:106: ElixirSense.Core.TypeInfo.get_signatures/3
(elixir_sense 2.0.0) lib/elixir_sense/providers/signature.ex:55: ElixirSense.Providers.Signature.find_signatures/5
(elixir_sense 2.0.0) lib/elixir_sense/providers/signature.ex:42: …
```
=> Fix for getting the typespec of `any()`

lib/elixir_sense.ex, lib/elixir_sense/core/module_store.ex, lib/elixir_sense/plugins/ecto.ex, lib/elixir_sense/plugins/ecto/schema.ex, lib/elixir_sense/plugins/ecto/types.ex, lib/elixir_sense/plugins/plugin.ex, lib/elixir_sense/providers/suggestion.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/generic_reducer.ex, test/elixir_sense/providers/suggestion_test.exs
This is a new PR based on this: https://github.com/elixir-lsp/elixir_sense/pull/139
Unfortunately, I don't think we can automatically find all extensions that are loaded since likely those extensions will be defined by your dependencies, and so some explicit configuration is needed. I went the simplest route possible here, and just expected `config :elixir_sense, :plugins`, which is actually a bit problematic because you get a warning about using that app in config w/o including it in deps.
I'm open to ideas on how to actually do the configuration.
Because we can't do it via automatically finding them, the `module_store` is technically unnecessary to make this work since I just used an explicit list. However, it seems like an optimization we wanted anyway, so I've left it in here.
=> improvement: support external plugins

lib/elixir_sense/core/module_store.ex
I'm noticing flakiness in plugin finding logic when we build our module store but don't ensure that the modules are compiled. I'm not sure what kind of overhead this will add, but by using `Code.ensure_compiled` instead of `Code.ensure_compiled!` this should at least not incur any deadlocks, and if we call it on all relevant modules iteratively, by the time we're done all deadlock modules should have been resolved.
=> fix: ensure modules are compiled when indexing modules

lib/elixir_sense/core/source.ex, test/elixir_sense/core/source_test.exs
Get documentation when hovering the functions inside string interpolation.
related issue https://github.com/elixir-lsp/vscode-elixir-ls/issues/185
=> don't replace string interpolation

lib/elixir_sense/core/introspection.ex
In some case, `NormalizedCode.getDocs()` would return results that include `:group` in the results. Since there was no matching `get_metadata_entry_md` for group, it would fail. This PR adds the appropriate match as well as a nonmatching path.
=> Include handling for group metadata in introspection.ex

lib/elixir_sense.ex, lib/elixir_sense/core/references_tracer.ex, lib/elixir_sense/providers/references.ex, test/elixir_sense/references_test.exs, test/support/references_tracer.ex
Supersedes https://github.com/elixir-lsp/elixir_sense/pull/80
I ended up using a tracer process only in tests. The assumption here is that the client will run it's own tracer and provide trace data to elixir_sense
=> Introduce references tracer

lib/elixir_sense.ex, lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/parser.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/suggestion.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/reducers/common.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/core/metadata_test.exs, test/elixir_sense/providers/suggestion/complete_test.exs
Basic code to find modules that require adding an alias. Sort of related to [elixir-ls issue](https://github.com/elixir-lsp/elixir-ls/issues/161)
~Marking it draft due to some known test failures that I would like to get some suggestions on how to handle them.~
=> find elixir modules that require adding an alias

lib/elixir_sense/core/module_store.ex, lib/elixir_sense/providers/suggestion.ex
So the problem with the existing implementation of plugins that live outside of ElixirSense (a problem that I created 😄 ) is that, unless you want your external hex package to have an explicit dependency on `elixir_sense`, you're going to have to do something like this:
```elixir
{:elixir_sense, ..., only: [:dev, :test]}
```
And then in your code that defines the plugin, you'll need to do something like:
```elixir
if Code.ensure_compiled?(ElixirSense.Plugin) do
defmodule MyApp.Plugin do
end
end
```
If you don't do that, then users who use your plugin *without* including `{:elixir_sense, ...}` as a dev dependency will get errors.
*BUT* then you run into the issue that if they don't include `{:elixir_sense, ...}` as a dev dependency, then the plugin won't be compiled at all, and so …
=> allow for plugins not using the ElixirSense.Plugin `@behaviour`

config/config.exs, config/dev.exs, config/prod.exs, config/test.exs, lib/elixir_sense/core/ast.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/log.ex, test/elixir_sense/log_test.exs
While using elixir-ls, frequently, the code that's sent to the LSP server (and then to elixir_sense) isn't always syntactically accurate, and sometimes elixir_sense will fail and spam the logs. After enough of these spammy logs, emacs throws the error into a mini-buffer to alert the user to some problem, which is not particularly helpful.
Emitting an error message in these circumstances is dubious, since there's nothing truly wrong, but I can understand that it might be helpful for other uses of elixir_ls. To that end, I consolidated the logging functions into a module and gated them with an application variable so that other apps can enable or disable logging at their discretion.
=> Allowed logging of errors to be quieted.

lib/elixir_sense.ex, lib/elixir_sense/providers/definition.ex, test/elixir_sense/definition_test.exs
Previously find definition did not respect the arity of functions - it would just take you to the first matching function header.
This PR aims to make it respect the arity of functions when going to the definition
=> Find definition to respect function arity

lib/elixir_sense/core/type_info.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/reducers/struct.ex, test/elixir_sense/providers/suggestion/complete_test.exs, test/elixir_sense/suggestions_test.exs, test/support/stuct_with_typespec.ex
This PR adds struct property typespecs in completions when struct module defines a type `t()`
=> Struct field typespecs

lib/elixir_sense.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/source.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/definition.ex, lib/elixir_sense/providers/references.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/definition_test.exs, test/elixir_sense/references_test.exs, test/elixir_sense/suggestions_test.exs
I've made an attempt to fix the reference provider ([Issue #124](https://github.com/elixir-lsp/elixir_sense/issues/124)). I've described part of the changes below since they needed to be applied in several places.  After that, the provider should cover many cases that are handled incorrectly in the current implementation. 
---
`State.new_func_vars_scope` had a different behavior than `State.new_vars_scope` - the first one didn't increase the scope counter what I've changed. Previously all variables from all function headers were in the same scope. Now, it is changed and every function creates two new scopes:
- one for the function header
- one for the function body (to avoid handling `do ... end` differently for the functions; this part was already there)
I created a new function …
=> Fix variable references

lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, test/elixir_sense/core/metadata_builder_test.exs
submodule now properly sets alias in its own scope (introduced in https://github.com/elixir-lsp/elixir_sense/pull/18/commits/9de7dd87ae79bd7e6db6e45dca3230e2cb6938da) submodule overwrites alias
external submodule unaliases
See discussions in https://github.com/elixir-lang/elixir/pull/12451
=> Fix submodule implicit alias behavior

lib/elixir_sense/providers/references.ex, test/support/references_tracer.ex
remove imported_call tracking, add missing local_call tracing in test
Partial fix for https://github.com/elixir-lsp/elixir-ls/issues/842
=> Do not crash references when call has nil line

lib/elixir_sense/core/introspection.ex, mix.exs, test/elixir_sense/core/parser_test.exs, test/elixir_sense/providers/suggestion/complete_test.exs
Elixir 1.15 prunes "unused" code paths by default, which lets the tests fail. Settings `prune_code_paths: false` for tests avoids that.
OTP 26 changed the Map behaviour when converting them to lists (there isn't a stable sorting anymore). This PR fixes the affected tests.
It also removed some modules used for autocompletion tests. I switched them to the `:logger` module.
There is also a problem with `ssl_verify_fun` (see https://github.com/deadtrickster/ssl_verify_fun.erl/pull/27) which is used by excoveralls. The explicit dependency to `:ssl_verify_fun` can be removed as soon as the PR is merged and a new version is released.
=> Fix tests for Elixir 1.15 and OTP 26

lib/elixir_sense/core/builtin_attributes.ex, lib/elixir_sense/providers/docs.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/reducers/common.ex, test/elixir_sense/docs_test.exs, test/elixir_sense/providers/suggestion/complete_test.exs, test/elixir_sense/suggestions_test.exs
=> Add documentation retrieval for module's built-in attributes

lib/elixir_sense/providers/suggestion/complete.ex, test/elixir_sense/providers/suggestion/complete_test.exs, test/elixir_sense/suggestions_test.exs
=> Fix Elixir root module suggestions

lib/elixir_sense/core/metadata_builder.ex, test/elixir_sense/core/metadata_builder_test.exs
=> Fix metadata builder to correctly handle pin operator

lib/elixir_sense/location.ex, test/elixir_sense/location_test.exs, test/misc/mock_elixir_src/lib/elixir/lib/string.ex
Greetings!
`elixir_sense` uses `mod.module_info(:compile)[:source]` in order to retrieve the source file for a module. While it works for regular Elixir files and dependencies, it fails for the Elixir sources (i.e., for the applications like `:elixir`, `:ex_unit`, `:eex` that ship with Elixir) if Elixir was built in a sandboxed environment. That happens, for example, on NixOS as it returns a path to a build location that no longer exists:
```iex
iex(1)> String.module_info(:compile)[:source]
'/build/source/lib/elixir/lib/string.ex'
```
("/build/source" refers to a location that contained Elixir source while it was being built inside a sandbox.)
Despite that, on NixOS it's easy to install the Elixir source as a package and provide the path to it as an environment variable.
<details> …
=> Allow to lookup Elixir source files under configured location

lib/elixir_sense/core/binding.ex, test/elixir_sense/suggestions_test.exs
As shown in the following code:
```
defmodule Mod do
@spec fun() :: NaiveDateTime.t()
def fun(), do: NaiveDateTime.new(1, 2)
def some do
var = fun()
var.h
end
end
```
It should be able to suggest from NaiveDateTime.
This wasn't working before because the `__aliases__` weren't being handled:
```
iex(1)> Code.string_to_quoted("@spec fun() :: NaiveDateTime.t()")
{:ok,
{:@, [line: 1],
[
{:spec, [line: 1],
[
{:"::", [line: 1],
[
{:fun, [line: 1], []},
{{:., [line: 1], [{:__aliases__, [line: 1], [:NaiveDateTime]}, :t]},
[line: 1], []}
]}
]}
]}}
```
=> Fix suggestions when using typespecs returning a remote type

lib/elixir_sense/core/source.ex, lib/elixir_sense/plugins/phoenix.ex, lib/elixir_sense/plugins/phoenix/scope.ex, lib/elixir_sense/providers/definition.ex, test/elixir_sense/definition_test.exs, test/elixir_sense/plugins/phoenix/scope_test.exs, test/elixir_sense/plugins/phoenix_test.exs, test/support/plugins/phoenix/page_controller.ex, test/support/plugins/phoenix/router.ex
This PR has two features:
1. Enable Go To Definition when inside a Phoenix `scope`;
2. Override Auto Complete for the controller argument if the function is one of the predefined ones from Phoenix.Route;
3. Override Auto Complete for the action argument if the function is one of the predefined ones from Phoenix.Route.
The PR is in draft, anything can be discussed. I though this could be a valuable contribution given the widespread usage of Phoenix.
=> Improve Phoenix integration

lib/elixir_sense/plugins/phoenix/scope.ex, lib/elixir_sense/providers/definition.ex
Fixes https://github.com/elixir-lsp/elixir_sense/issues/284
=> Phoenix scopes fixes

lib/elixir_sense/core/applications.ex, lib/elixir_sense/core/erlang_html.ex, lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/normalized/code.ex, lib/elixir_sense/providers/docs.ex, test/elixir_sense/core/erlang_html_test.exs, test/elixir_sense/docs_test.exs, test/elixir_sense/signature_test.exs, test/elixir_sense/suggestions_test.exs
fix rendering of links in erlang docs
Reference
https://www.erlang.org/doc/apps/erl_docgen/inline_tags#%3Csee*%3E---see-tags
=> Add support for rendering erlang see tags

lib/elixir_sense/core/metadata.ex, lib/elixir_sense/core/metadata_builder.ex, lib/elixir_sense/core/state.ex, lib/elixir_sense/providers/docs.ex, lib/elixir_sense/providers/signature.ex, lib/elixir_sense/providers/suggestion/complete.ex, lib/elixir_sense/providers/suggestion/reducers/overridable.ex, lib/elixir_sense/providers/suggestion/reducers/type_specs.ex, test/elixir_sense/core/metadata_builder_test.exs, test/elixir_sense/docs_test.exs, test/elixir_sense/signature_test.exs, test/elixir_sense/suggestions_test.exs, test/support/overridable_function.ex
Emit docs and meta on local buffer code in providers
Fixes https://github.com/elixir-lsp/elixir_sense/issues/273
Fixes https://github.com/elixir-lsp/elixir_sense/issues/261
Addresses https://github.com/elixir-lsp/elixir-ls/issues/932
=> Collect docs and metadata in metadata builder

lib/elixir_sense/core/state.ex
Previously, an issue with the interpolation of the raised exception (`Exception.blame/3` returns a tuple) caused `format_doc_arg` to raise an unrelated error.
=> Do not raise while handling exception in format_doc_arg

lib/elixir_sense/providers/completion/completion_engine.ex
We ran into an issue in Lexical reported here: https://github.com/lexical-lsp/lexical/issues/805
Lexical is packaged by precompiling everything, usually on the lowest supported version of Elixir/OTP, and then injecting those compiled modules when launching the runtime node where user project code runs. This means that compile-time version checks could lead to an unexpected code branch at runtime, as the runtime might be a later version.
I think this would *usually* be okay, since compile-time version checks are usually there to use new APIs and fall back to ones that would still work, but in this case, a private API (`Code.Identifier.classify`) was being used that no longer exists in 1.14+.
I know this code-path is performance-sensitive, but a quick Benchee shows that …
=> Use a runtime check for `Macro.classify_atom/1`

lib/elixir_sense/providers/plugins/module_store.ex
The plugin module was renamed from `ElixirSense.Plugin` to `ElixirLS.LanguageServer.Plugin`, to `ElixirSense.Providers.Plugin` (both renames broke spark's plugin, not a big deal but if you can try not to rename those modules w/o letting me know so I can get ahead of it w/ a release of spark, that would be great.)
However, the new behaviour module is not in the list used to detect a plugin, so I have to use a behaviour that doesn't exist.
Additionally, module attributes from `.module_info` that are persisted appear (or can appear) as lists, and so we need to update the way we check for those flags.
This stuff has a lot of cruft, and I fully understand if we need to change it in the future, and I'm happy to participate in whatever changes we want to make. I know that there are likely …
=> fix: include new plugin behaviour in detection list
