elixir-lsp/elixir_sense

- lib/elixir_sense.ex
- test/elixir_sense/core/metadata_builder_test.exs
- test/server_test.exs
Looks like I missed some in #4
> Fix more tests that required access to source

- lib/elixir_sense/server/tcp_server.ex
`System.tmp_dir/1` provides tmp dir in different OSs
> create the socket in system tmp dir

- .tool-versions
- .travis.yml
- lib/elixir_sense.ex
- lib/elixir_sense/core/ast.ex
- lib/elixir_sense/core/introspection.ex
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/docs_test.exs
- test/elixir_sense/providers/suggestion_test.exs
- test/elixir_sense/suggestions_test.exs
Fixes tests depending on documentation and specs
Fixes behaviour extraction and generation of suggestions depending on behaviour callbacks
Fixes extraction of specs with union of clauses
> Elixir 1.9 compatibility

- lib/elixir_sense/core/parser.ex
- test/elixir_sense/core/parser_test.exs
Fixes https://github.com/elixir-lsp/elixir-ls/issues/17
> Fix crash when handling malformed do expression syntax error

- lib/elixir_sense/core/metadata_builder.ex
- test/elixir_sense/docs_test.exs
Fixes https://github.com/elixir-lsp/elixir_sense/issues/34
> fix crash when `use` in `Elixir` module

- lib/elixir_sense/core/state.ex
- test/elixir_sense/core/metadata_builder_test.exs
Fixes https://github.com/elixir-lsp/elixir_sense/issues/32
> fix crash with nested 1.2 alias syntax

- lib/elixir_sense/providers/suggestion.ex
- test/elixir_sense/suggestions_test.exs
Fixes https://github.com/elixir-lsp/elixir_sense/issues/47
> do not suggest callbacks when behaviour is not a module

- lib/elixir_sense/core/type_info.ex
- test/elixir_sense/suggestions_test.exs
Fall back to typespec if no docs available.
> Provide completions for erlang types

- test/elixir_sense/docs_test.exs
> Run mix format

- .travis.yml
Also added `_build/dev` to travis cache, to cache PLTs, required for faster builds
> Add dialyzer to travis

- README.md
Build broke but unrelated to this PR, fix here: https://github.com/elixir-lsp/elixir_sense/pull/82
> Fix github url on README

- lib/elixir_sense/core/ast.ex
- lib/elixir_sense/core/metadata_builder.ex
- lib/elixir_sense/core/parser.ex
- lib/elixir_sense/providers/expand.ex
- lib/elixir_sense/server/tcp_server.ex
- mix.exs
- test/elixir_sense/eval_test.exs
All is green now but I will wait with merging this until rc is released
> Elixir 1.11 support

- lib/elixir_sense/plugins/ecto/query.ex
- test/elixir_sense/plugins/ecto_test.exs
> [Ecto] - Fix listing bindings of namespaced modules

- .github/workflows/ci.yml
> update ci to use erlang foundation version

- lib/elixir_sense/plugins/option.ex
- test/elixir_sense/plugins/ecto_test.exs
Hi there! 
A small improvement related to https://github.com/elixir-lsp/elixir_sense/pull/121. I'd like to continue working through the list, seems like a good functionality to get started with.
> Add fuzzy matching to option plugin

- lib/elixir_sense/providers/suggestion/reducers/struct.ex
- lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- test/elixir_sense/suggestions_test.exs
> Add fuzzy matching to typespecs and structs

- lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
- lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
- lib/elixir_sense/providers/suggestion/reducers/overridable.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/protocol.ex
- test/elixir_sense/suggestions_test.exs
* Callbacks
* Documentation snippets
* Overridable
* Params
* Protocol
> Add more fuzzy matching

- .credo.exs
- .github/workflows/ci.yml
- lib/elixir_sense/core/applications.ex
- lib/elixir_sense/core/builtin_types.ex
- lib/elixir_sense/core/erlang_html.ex
- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/core/metadata.ex
- lib/elixir_sense/core/normalized/code.ex
- lib/elixir_sense/core/type_info.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- run.exs
- test/elixir_sense/core/erlang_html_test.exs
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/core/normalized/code_test.exs
- test/elixir_sense/docs_test.exs
- test/elixir_sense/providers/suggestion/complete_test.exs
- test/elixir_sense/signature_test.exs
- test/elixir_sense/suggestions_test.exs
- test/support/module_with_typespecs.ex
- test/test_helper.exs
Fixes https://github.com/elixir-lsp/elixir_sense/issues/114
> Erlang eep48

- lib/elixir_sense/core/binding.ex
- lib/elixir_sense/core/metadata_builder.ex
- lib/elixir_sense/core/state.ex
- test/elixir_sense/core/binding_test.exs
- test/elixir_sense/core/metadata_builder_test.exs
- test/support/functions_with_return_spec.ex
Statically determine types in list operations
Determine types in for and with expressions
> List destructuring

- lib/elixir_sense/core/behaviours.ex
- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/core/normalized/code.ex
- lib/elixir_sense/core/type_info.ex
- lib/elixir_sense/providers/implementation.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- test/elixir_sense/core/metadata_builder_test.exs
- test/elixir_sense/docs_test.exs
- test/elixir_sense/signature_test.exs
- test/elixir_sense/suggestions_test.exs
- test/support/example_behaviour.ex
provide in docs, specs and completions
Fixes https://github.com/elixir-lsp/elixir_sense/issues/163
> Extract typespec for callback implementations from behaviours

- lib/elixir_sense/core/metadata_builder.ex
- lib/elixir_sense/core/state.ex
- test/elixir_sense/definition_test.exs
- test/elixir_sense/references_test.exs
Handling pinned variables to fix [#179](https://github.com/elixir-lsp/elixir_sense/issues/179).
> Stop making pinned variables defined

- lib/elixir_sense.ex
- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/plugins/ecto/query.ex
- lib/elixir_sense/plugins/util.ex
- lib/elixir_sense/providers/definition.ex
- lib/elixir_sense/providers/docs.ex
- lib/elixir_sense/providers/implementation.ex
- lib/elixir_sense/providers/references.ex
- lib/elixir_sense/providers/signature.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- lib/elixir_sense/providers/suggestion/reducers/common.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/providers/suggestion/complete_test.exs
- test/elixir_sense/providers/suggestion_test.exs
- test/elixir_sense/signature_test.exs
- test/elixir_sense/suggestions_test.exs
do not return info about not required modules
return needed require on completions
Fixes https://github.com/elixir-lsp/elixir_sense/issues/182
> Respect require

- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/core/metadata_builder.ex
- lib/elixir_sense/core/source.ex
- lib/elixir_sense/core/state.ex
- lib/elixir_sense/plugins/ecto/query.ex
- lib/elixir_sense/plugins/util.ex
- lib/elixir_sense/providers/definition.ex
- lib/elixir_sense/providers/docs.ex
- lib/elixir_sense/providers/implementation.ex
- lib/elixir_sense/providers/references.ex
- lib/elixir_sense/providers/signature.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/core/metadata_builder_test.exs
- test/elixir_sense/core/source_test.exs
- test/elixir_sense/definition_test.exs
- test/elixir_sense/suggestions_test.exs
Addresses https://github.com/elixir-lsp/elixir_sense/issues/194
Fixes https://github.com/elixir-lsp/elixir_sense/issues/193
> Introduce typespec scope

- lib/elixir_sense.ex
- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/core/metadata.ex
- lib/elixir_sense/core/metadata_builder.ex
- lib/elixir_sense/core/normalized/code.ex
- lib/elixir_sense/core/parser.ex
- lib/elixir_sense/core/type_info.ex
- lib/elixir_sense/location.ex
- lib/elixir_sense/providers/definition.ex
- lib/elixir_sense/providers/docs.ex
- lib/elixir_sense/providers/implementation.ex
- lib/elixir_sense/providers/references.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/core/parser_test.exs
- test/elixir_sense/definition_test.exs
- test/elixir_sense/docs_test.exs
- test/elixir_sense/implementation_test.exs
- test/elixir_sense/references_test.exs
- test/elixir_sense/suggestions_test.exs
- test/support/behaviour_implementations.ex
- test/support/functions_with_default_args.ex
- test/support/module_with_functions.ex
- test/support/types_with_multiple_arity.ex
Fixes https://github.com/elixir-lsp/elixir_sense/issues/28
Fixes https://github.com/elixir-lsp/elixir_sense/issues/241
Fixes https://github.com/elixir-lsp/elixir_sense/issues/243
Fixes https://github.com/elixir-lsp/elixir_sense/issues/244
> Use call arity

- lib/elixir_sense.ex
- lib/elixir_sense/core/introspection.ex
- lib/elixir_sense/core/metadata.ex
- lib/elixir_sense/core/state.ex
- lib/elixir_sense/core/type_info.ex
- lib/elixir_sense/providers/docs.ex
- lib/elixir_sense/providers/implementation.ex
- lib/elixir_sense/providers/signature.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- lib/elixir_sense/providers/suggestion/reducers/common.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/struct.ex
- test/elixir_sense/core/introspection_test.exs
- test/elixir_sense/core/metadata_test.exs
- test/elixir_sense/docs_test.exs
- test/elixir_sense/providers/suggestion/complete_test.exs
- test/elixir_sense/signature_test.exs
- test/elixir_sense/suggestions_test.exs
- test/support/example_behaviour.ex
Fixes https://github.com/elixir-lsp/elixir_sense/issues/224
> Provide specs from behaviour for local buffer code
